// Dashboard sin estado de servidor: refresca los datos desde la API de AQUASAVE.
const api = '/api';
const levelValue = { BAJO: 1, MEDIO: 2, ALTO: 3 };
let map, markers, chart, devices = [], measurements = [];

function formatDate(date) { return new Date(date).toLocaleString('es-AR', { dateStyle: 'short', timeStyle: 'medium' }); }
function escapeHtml(text) { const box = document.createElement('div'); box.textContent = text ?? ''; return box.innerHTML; }
function createMap() { map = L.map('map').setView([-34.6037, -58.3816], 11); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '© OpenStreetMap' }).addTo(map); markers = L.layerGroup().addTo(map); }
function updateMap() { markers.clearLayers(); const points = []; devices.forEach(d => { const level = d.ultima_medicion?.nivel || 'BAJO'; const icon = L.divIcon({ className: '', html: `<div class="marker ${level}"></div>`, iconSize:[17,17], iconAnchor:[8,8] }); L.marker([d.latitud,d.longitud], { icon }).bindPopup(`<b>${escapeHtml(d.nombre)}</b><br>${escapeHtml(d.ubicacion)}<br>Nivel: ${level}<br>${d.ultima_medicion ? `${d.ultima_medicion.distancia.toFixed(1)} cm` : 'Sin mediciones'}`).addTo(markers); points.push([d.latitud,d.longitud]); }); if (points.length) map.fitBounds(points, { padding:[35,35], maxZoom:15 }); }
function renderSummary() { document.querySelector('#device-count').textContent = devices.filter(d => d.activo).length; document.querySelector('#record-count').textContent = measurements.length; const high = measurements.find(m => m.nivel === 'ALTO'); document.querySelector('#last-alert').textContent = high ? formatDate(high.fecha_hora) : 'Sin alertas'; }
function renderDevices() { const target = document.querySelector('#device-cards'); if (!devices.length) { target.replaceChildren(document.querySelector('#empty').content.cloneNode(true)); return; } target.innerHTML = devices.map(d => { const m = d.ultima_medicion; return `<article class="device"><h3>${escapeHtml(d.nombre)}</h3>${m ? `<p><span class="pill ${m.nivel}">${m.nivel}</span></p><p>${m.distancia.toFixed(1)} cm · ${formatDate(m.fecha_hora)}</p>` : '<p>Sin mediciones</p>'}<p>${escapeHtml(d.ubicacion)}</p></article>`; }).join(''); }
function renderTable() { const target = document.querySelector('#history'); target.innerHTML = measurements.length ? measurements.map(m => { const d = devices.find(x => x.id === m.dispositivo_id); return `<tr><td>${formatDate(m.fecha_hora)}</td><td>${escapeHtml(d?.nombre || m.dispositivo_id)}</td><td><span class="pill ${m.nivel}">${m.nivel}</span></td><td>${m.distancia.toFixed(1)} cm</td></tr>`; }).join('') : '<tr><td colspan="4" class="empty">No hay mediciones para este filtro.</td></tr>'; }
function renderChart() { const ordered = [...measurements].reverse(); if (chart) chart.destroy(); chart = new Chart(document.querySelector('#chart'), { type:'line', data:{ labels:ordered.map(m => formatDate(m.fecha_hora)), datasets:[{ label:'Nivel de agua', data:ordered.map(m => levelValue[m.nivel]), borderColor:'#147ca5', backgroundColor:'#147ca530', tension:.25, fill:true, pointRadius:3 }] }, options:{ responsive:true, maintainAspectRatio:false, scales:{ y:{ min:.7,max:3.3,ticks:{ stepSize:1, callback:v => ({1:'BAJO',2:'MEDIO',3:'ALTO'})[v] || '' }, title:{ display:true,text:'Estado' } }, x:{ ticks:{ maxTicksLimit:6, maxRotation:0 } } }, plugins:{ legend:{ display:false }, tooltip:{ callbacks:{ label:ctx => ` ${ordered[ctx.dataIndex].nivel} · ${ordered[ctx.dataIndex].distancia.toFixed(1)} cm` } } } } }); }
async function loadData() { const id = document.querySelector('#device-filter').value; const [devicesResult, measuresResult] = await Promise.all([fetch(`${api}/dispositivos`), fetch(`${api}/mediciones?limit=200${id ? `&dispositivo_id=${encodeURIComponent(id)}` : ''}`)]); if (!devicesResult.ok || !measuresResult.ok) throw new Error('No se pudo conectar con la API'); devices = await devicesResult.json(); measurements = await measuresResult.json(); const select = document.querySelector('#device-filter'); const selected = select.value; select.innerHTML = '<option value="">Todos los dispositivos</option>' + devices.map(d => `<option value="${escapeHtml(d.id)}">${escapeHtml(d.nombre)} (${escapeHtml(d.id)})</option>`).join(''); select.value = selected; renderSummary(); renderDevices(); renderTable(); renderChart(); updateMap(); document.querySelector('#updated').textContent = `Actualizado: ${new Date().toLocaleTimeString('es-AR')}`; }
document.addEventListener('DOMContentLoaded', () => { createMap(); document.querySelector('#reload').addEventListener('click', () => loadData().catch(showError)); document.querySelector('#device-filter').addEventListener('change', () => loadData().catch(showError)); loadData().catch(showError); });
function showError(error) { document.querySelector('#updated').textContent = `Error: ${error.message}`; }
